"""fix FK match_id to match_pk_id

Revision ID: 1d554eb570d3
Revises: 731fce325231
Create Date: 2026-05-21 14:42:27.655097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d554eb570d3'
down_revision: Union[str, Sequence[str], None] = '731fce325231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_participants', sa.Column('match_pk_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_match_player'), 'match_participants', type_='unique')
    op.create_unique_constraint('uq_match_player', 'match_participants', ['match_pk_id', 'puuid'])
    op.drop_constraint(op.f('match_participants_match_id_fkey'), 'match_participants', type_='foreignkey')
    op.create_foreign_key(None, 'match_participants', 'game_matches', ['match_pk_id'], ['id'], ondelete='CASCADE')
    op.drop_column('match_participants', 'match_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_participants', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match_participants', type_='foreignkey')
    op.create_foreign_key(op.f('match_participants_match_id_fkey'), 'match_participants', 'game_matches', ['match_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_match_player', 'match_participants', type_='unique')
    op.create_unique_constraint(op.f('uq_match_player'), 'match_participants', ['match_id', 'puuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('match_participants', 'match_pk_id')
    # ### end Alembic commands ###
