"""remove player_id relation from match_participants and store all match participants

Revision ID: 4f1f22f2d821
Revises: e7e89f5a4632
Create Date: 2026-05-24 11:47:11.953747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1f22f2d821'
down_revision: Union[str, Sequence[str], None] = 'e7e89f5a4632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('match_participants_player_id_fkey'), 'match_participants', type_='foreignkey')
    op.drop_column('match_participants', 'player_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_participants', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('match_participants_player_id_fkey'), 'match_participants', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
