"""fix FK match_id to game_matches

Revision ID: 94c42c1e8e82
Revises: 476ceb5706d2
Create Date: 2026-05-21 12:05:38.688349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c42c1e8e82'
down_revision: Union[str, Sequence[str], None] = '476ceb5706d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
