"""Add unique constraint on player_id+queue_type

Revision ID: e7e89f5a4632
Revises: 1d554eb570d3
Create Date: 2026-05-22 16:28:00.388915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e89f5a4632'
down_revision: Union[str, Sequence[str], None] = '1d554eb570d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_participants', 'match_pk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_player_queue', 'ranked_entries', ['player_id', 'queue_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_player_queue', 'ranked_entries', type_='unique')
    op.alter_column('match_participants', 'match_pk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
